const express = require("express")
const bidrouter = express.Router()
const {addnewbid,getbids,getbidbyid,sendexample,deletebid,updatebid} = require("../controllers/productcontroller")
bidrouter.post("/create-bid",addnewbid)
bidrouter.get("/getall/bids",getbids)
bidrouter.get("/getbids/:id",getbidbyid)
bidrouter.delete("/delete/:id",deletebid)
bidrouter.put("/update-bid/:id",updatebid)
bidrouter.get("/getlooped",sendexample)
module.exports = {bidrouter};
